sonar.projectKey=Jagadeesh-Tadepalli-M_MyProject-Ledger-service

sonar.organization=jagadeesh-tadepalli-m

sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
